spring:
  application:
    name: simple-service
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.simple: DEBUG
